### ISSUE TITLE
Mambo Bot

### ISSUE THREAD

**Issue by MazinxGamer** [mrshankly/mambo#10]
How i Can Run it on Linux CentOS 6

**Comment by MazinxGamer** [comment]
Please Please respond quickly

**Comment by mrshankly** [comment]
Everything is in the [README.md](https://github.com/mrshankly/mambo/blob/master/README.md) file.

You will need elixir version 0.12.4 (which is quite old by now). Also, this project is abandoned, some people seem to have problems running this with the last teamspeak version. I'm not going to update this any more. Good luck.
