### ISSUE TITLE
Not working correctly with newest TS server version

### ISSUE THREAD

**Issue by schoerg** [mrshankly/mambo#8]
Hi

Mambo does not seem to work correctly with version 3.0.11.2.
I have entered multiple channels in the settings.json but uppon start it only switches to 1-2 channels. The bots who switched on themselves are working correctly, the rest is in the default channel. I can switch them to the channels I want them too, but no commands are working.

I don't know if you are still active on this project, but maybe you'll find time for this.

**Comment by mrshankly** [comment]
I need more information.

Did it work before 3.0.11.2?
Are all channel ids valid in the settings.json file?
Does it work if you use the string `"all"` instead of a list of channel ids?

**Comment by schoerg** [comment]
Yes, it worked with version 3.0.10.

Yes the channel ids are valid.
It works halfway with string "all", some channels are not populated by the bot, there seems to be a lot more serverquery instances then they are channels, see the two screenshot.
With this setting more bots seem to be working, I haven't tested every channel, the instances in the default channel don't respond to ".help"

![2015-03-15_21-40-34-i3l8](https://cloud.githubusercontent.com/assets/4064778/6658012/26c1f5be-cb5c-11e4-9c18-898c488cf8cd.png)

![2015-03-15_21-40-51-b2d8](https://cloud.githubusercontent.com/assets/4064778/6658013/2cd26d58-cb5c-11e4-9036-a49597e5cf4c.png)

**Comment by mrshankly** [comment]
If you start the bot with `iex -S mix` (double Ctrl+c to exit the shell) does it print any error message?

**Comment by schoerg** [comment]
```
Erlang R16B02-basho5 (erts-5.10.3) [source] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (0.10.4-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```

No.

**Comment by schoerg** [comment]
Here is the serverlog from starting up Mambo:

http://pastebin.com/77fQALvd

(The last server edit by me was disabling Serverquery logging)

**Comment by mrshankly** [comment]
Ok, I'll try to get some time during this week to see if I can fix it. It's
been a while since I used the bot and teamspeak.

**Comment by schoerg** [comment]
Thank you.

One thing I also noticed just now: Some (not sure if all) disconnected and reconnected after ~10 minutes of starting the bot.

Pastebin:
http://pastebin.com/qGzxUyyn

**Comment by S4M04NSL4Y3R** [comment]
@schoerg What version of Elixer and Erlang are you using?

I am able to compile but an error is thrown when trying to start the bot. You seem to be getting further than I am.

@mrshankly Your TS3 Bot is exactly what I was looking for. Thank you for the time you put in, especially when you're not actively using it anymore.

**Comment by schoerg** [comment]
@S4M04NSL4Y3R
Elixir (0.10.4-dev)
Erlang R16B02-basho5 (erts-5.10.3)

**Comment by schoerg** [comment]
Kindly asking if you had any time looking into this.

**Comment by bzyg7b** [comment]
How can I find and install Elixir (0.10.4-dev) I have Erlang R16B02-basho5 (erts-5.10.3) but not Elixir :cry:
