### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by davoz96** [mrshankly/mambo#9]
Hi,
i get this error while compiling with mix:
ERROR: OTP release 17 does not match required regex R15|R16|R17
ERROR: compile failed while processing /root/mambo-master/deps/hackney_lib: rebar_abort
** (Mix) Could not compile dependency hackney_lib, /usr/bin/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile hackney_lib

What does it means?

**Comment by Sonicr343** [comment]
"ERROR: OTP release 17 does not match required regex R15:R16:R17"
Is in regards to erlang. I had to install R16 for it to compile with mix. https://www.erlang-solutions.com/downloads/download-erlang-otp 
You can download it from here, I would go with R16B02.

**Comment by bzyg7b** [comment]
got this error and fixed by installing the older version now i get this 

    ERROR: compile failed while processing /home/ubuntu/1/mambo-master/deps/mimetypes: rebar_abort
    ** (Mix) Could not compile dependency mimetypes, /home/ubuntu/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile mimetypes
